(() => {
  'use strict';
  const REGISTRY_KEY = 'xi.xi.sites.v1';
  const THEME_KEY = 'domPipe.api-workspace.theme';
  const STATE_KEY = 'xi.webapps.control-state.v1';
  const DEMO_SITES = [
    { id:'demo-console', name:'XI Demo Console', url:'http://127.0.0.1:8787/xi-demo/', environment:'DEMO', version:'2.8.3', digest:'sha256:7fa2c1d8', heartbeat:'12 sec ago', status:'ready', users:128, clients:42, rpm:318, errors:'0.18%', lastDeploy:'2026-08-02 13:42 UTC' },
    { id:'landing', name:'Public landing', url:'https://example.invalid/landing/', environment:'PRODUCTION', version:'1.14.0', digest:'sha256:94bc18ef', heartbeat:'41 sec ago', status:'ready', users:64, clients:18, rpm:96, errors:'0.04%', lastDeploy:'2026-08-01 18:09 UTC' },
    { id:'checkout', name:'Checkout flow', url:'https://example.invalid/cart/', environment:'STAGING', version:'0.9.7-rc2', digest:'sha256:24d9aa02', heartbeat:'2 min ago', status:'paused', users:0, clients:0, rpm:0, errors:'—', lastDeploy:'2026-07-30 09:16 UTC' }
  ];
  const CLIENTS = [
    ['Maya Chen','sess_8F2A','Chrome 126 · macOS','Brooklyn, NY','18 sec ago','ACTIVE'],
    ['Jon Bell','sess_71C0','Edge 126 · Windows','Austin, TX','34 sec ago','ACTIVE'],
    ['A. Okafor','sess_0D92','Safari · iPhone 15','London, UK','1 min ago','IDLE'],
    ['studio-bot','sess_BB19','Firefox · Linux','Frankfurt, DE','2 min ago','ACTIVE']
  ];
  const $ = id => document.getElementById(id);
  const read = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key) || 'null'); return value ?? fallback; } catch { return fallback; } };
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const escapeHtml = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const sitesFromRegistry = () => { const saved = read(REGISTRY_KEY, []); if (!Array.isArray(saved) || !saved.length) return DEMO_SITES; return saved.map((site, index) => ({ ...DEMO_SITES[index % DEMO_SITES.length], id:String(site?.id || site?.url || `site-${index}`), name:String(site?.name || site?.url || `Registered site ${index + 1}`), url:String(site?.url || '') })); };
  const sites = sitesFromRegistry();
  let selected = null;
  let localState = read(STATE_KEY, {});
  let toastTimer;
  function currentSite() { return sites.find(site => site.id === selected) || sites[0]; }
  function renderList() { $('siteCount').textContent = sites.length; $('registryLabel').textContent = localStorage.getItem(REGISTRY_KEY) ? `${sites.length} registered sites` : 'Demo registry fallback'; $('webappList').innerHTML = sites.map(site => `<button class="webapp-item ${site.id === selected ? 'active' : ''}" data-site-id="${escapeHtml(site.id)}" type="button"><strong>${escapeHtml(site.name)}</strong><small>${escapeHtml(site.url || 'URL not provided')}</small><span class="webapp-item-meta"><span class="mini-status ${site.status === 'paused' ? 'paused' : ''}">● ${site.status === 'paused' ? 'PAUSED' : 'READY'}</span><span>${site.users || 0} users</span></span></button>`).join(''); }
  function siteState(site) { const saved = localState[site.id] || {}; return { ...site, ...saved, status: saved.status || site.status || 'ready' }; }
  function renderSite() { const site = siteState(currentSite()); const paused = site.status === 'paused'; $('siteName').textContent = site.name; $('siteUrl').textContent = site.url || 'No URL registered'; $('siteEnvironment').textContent = site.environment || 'REGISTERED'; $('siteHeartbeat').textContent = `heartbeat ${site.heartbeat || 'not reported'}`; $('siteStatus').textContent = paused ? 'PAUSED' : 'READY'; $('siteStatus').classList.toggle('paused', paused); $('healthStatus').textContent = paused ? 'PAUSED' : 'HEALTHY'; $('healthStatus').classList.toggle('paused', paused); $('endpointHealth').textContent = paused ? '503 / paused locally' : '200 / healthy'; $('deploymentDigest').textContent = site.digest || 'sha256:unavailable'; $('siteVersion').textContent = site.version || 'unreported'; $('lastDeploy').textContent = site.lastDeploy || 'unreported'; $('activeUsers').textContent = paused ? '0' : site.users ?? '—'; $('connectedClients').textContent = paused ? '0' : site.clients ?? '—'; $('requestsPerMinute').textContent = paused ? '0' : site.rpm ?? '—'; $('errorRate').textContent = site.errors ?? '—'; $('clientState').textContent = paused ? 'CLIENTS PAUSED' : 'DEMO TELEMETRY'; $('clientTable').innerHTML = CLIENTS.map(client => `<tr><td><span class="session-user">${client[0]}</span><span class="session-id">${client[1]}</span></td><td>${client[2]}</td><td>${client[3]}</td><td class="mono">${client[4]}</td><td><span class="client-state ${client[5] === 'IDLE' || paused ? 'idle' : ''}">${paused ? 'PAUSED' : client[5]}</span></td></tr>`).join(''); renderList(); }
  function events() { return localState[currentSite().id]?.events || [{ title:'Heartbeat received', detail:'Demo telemetry connected · 200 OK', time:'12 sec ago' }, { title:'Deployment verified', detail:'Digest matches registered release', time:'18 min ago' }, { title:'Operator session opened', detail:'Local simulation mode', time:'Today, 13:44' }]; }
  function renderEvents() { $('activityFeed').innerHTML = events().slice(0,8).map(event => `<article class="timeline-item"><span class="timeline-dot"></span><div><strong>${escapeHtml(event.title)}</strong><p>${escapeHtml(event.detail)}</p></div><time class="timeline-time">${escapeHtml(event.time)}</time></article>`).join(''); }
  function showToast(message) { $('toast').textContent = message; $('toast').classList.add('visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').classList.remove('visible'), 3200); }
  function addEvent(title, detail) { const id = currentSite().id; const state = localState[id] || {}; state.events = [{ title, detail, time:'just now' }, ...events()]; localState[id] = state; write(STATE_KEY, localState); renderEvents(); }
  function confirmAction(title, copy, callback) { $('dialogTitle').textContent = title; $('dialogCopy').textContent = copy; const dialog = $('operatorDialog'); $('dialogConfirm').onclick = () => { callback(); dialog.close(); }; dialog.showModal(); }
  function runAction(action) { const site = currentSite(); if (action === 'pause' || action === 'resume') { const next = action === 'pause' ? 'paused' : 'ready'; confirmAction(`${action === 'pause' ? 'Pause' : 'Resume'} ${site.name}?`, action === 'pause' ? 'New sessions will be marked paused in this local simulation.' : 'Sessions will be marked ready again in this local simulation.', () => { localState[site.id] = { ...(localState[site.id] || {}), status:next, events:localState[site.id]?.events }; write(STATE_KEY, localState); addEvent(action === 'pause' ? 'Webapp paused' : 'Webapp resumed', 'Local simulation · no remote request sent'); renderSite(); showToast(action === 'pause' ? 'Webapp paused locally' : 'Webapp resumed locally'); }); return; } if (action === 'notice') { const message = window.prompt('Maintenance notice (local demo only):', 'Planned maintenance begins at 22:00 UTC.'); if (message?.trim()) { addEvent('Maintenance notice drafted', message.trim()); showToast('Notice added to local audit feed'); } return; } if (action === 'refresh') { addEvent('Client refresh requested', 'Local simulation · 4 demo sessions marked for refresh'); showToast('Refresh request simulated locally'); } }
  function init() { const params = new URLSearchParams(location.search); selected = params.get('site') || sites[0].id; if (!sites.some(site => site.id === selected)) selected = sites[0].id; const theme = localStorage.getItem(THEME_KEY) || 'dark'; document.documentElement.dataset.theme = theme; renderSite(); renderEvents(); $('webappList').addEventListener('click', event => { const item = event.target.closest('[data-site-id]'); if (!item) return; selected = item.dataset.siteId; const url = new URL(location.href); url.searchParams.set('site', selected); history.replaceState(null, '', url); renderSite(); renderEvents(); }); document.querySelector('.action-list').addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (button) runAction(button.dataset.action); }); $('clearEvents').addEventListener('click', () => { const id = currentSite().id; localState[id] = { ...(localState[id] || {}), events:[] }; write(STATE_KEY, localState); renderEvents(); showToast('Local activity feed cleared'); }); $('themeToggle').addEventListener('click', () => { const next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = next; localStorage.setItem(THEME_KEY, next); }); }
  document.addEventListener('DOMContentLoaded', init);
})();
