(() => {
  'use strict';
  const REGISTRY_KEY = 'xi.xi.sites.v1';
  const THEME_KEY = 'domPipe.api-workspace.theme';
  const STATE_KEY = 'xi.webapps.control-state.v1';
  const SERVER_URL_PREFIX = 'xi.webapps.server-url.';
  const ENDPOINT_PREFIX = 'xi.webapps.endpoint.';
  const DEMO_SITES = [
    { id:'demo-console', name:'XI Demo Console', url:'http://127.0.0.1:8787/xi-demo/', environment:'DEMO', version:'2.8.3', digest:'sha256:7fa2c1d8', heartbeat:'12 sec ago', status:'ready', users:128, clients:42, rpm:318, errors:'0.18%', lastDeploy:'2026-08-02 13:42 UTC' },
    { id:'landing', name:'Public landing', url:'https://example.invalid/landing/', environment:'PRODUCTION', version:'1.14.0', digest:'sha256:94bc18ef', heartbeat:'41 sec ago', status:'ready', users:64, clients:18, rpm:96, errors:'0.04%', lastDeploy:'2026-08-01 18:09 UTC' },
    { id:'checkout', name:'Checkout flow', url:'https://example.invalid/cart/', environment:'STAGING', version:'0.9.7-rc2', digest:'sha256:24d9aa02', heartbeat:'2 min ago', status:'paused', users:0, clients:0, rpm:0, errors:'—', lastDeploy:'2026-07-30 09:16 UTC' }
  ];
  const CLIENTS = [
    ['Maya Chen','sess_8F2A','Chrome 126 · macOS','Brooklyn, NY','18 sec ago','ACTIVE'],
    ['Jon Bell','sess_71C0','Edge 126 · Windows','Austin, TX','34 sec ago','ACTIVE'],
    ['A. Okafor','sess_0D92','Safari · iPhone 15','London, UK','1 min ago','IDLE'],
    ['studio-bot','sess_BB19','Firefox · Linux','Frankfurt, DE','2 min ago','ACTIVE']
  ];
  const $ = id => document.getElementById(id);
  const read = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key) || 'null'); return value ?? fallback; } catch { return fallback; } };
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const escapeHtml = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const sitesFromRegistry = () => { const saved = read(REGISTRY_KEY, []); if (!Array.isArray(saved) || !saved.length) return DEMO_SITES; return saved.map((site, index) => ({ ...DEMO_SITES[index % DEMO_SITES.length], id:String(site?.id || site?.url || `site-${index}`), name:String(site?.name || site?.url || `Registered site ${index + 1}`), url:String(site?.url || '') })); };
  const sites = sitesFromRegistry();
  let selected = null;
  let localState = read(STATE_KEY, {});
  const remoteStates = {};
  let toastTimer;
  function currentSite() { return sites.find(site => site.id === selected) || sites[0]; }
  function renderList() { $('siteCount').textContent = sites.length; $('registryLabel').textContent = localStorage.getItem(REGISTRY_KEY) ? `${sites.length} registered sites` : 'Demo registry fallback'; $('webappList').innerHTML = sites.map(site => `<button class="webapp-item ${site.id === selected ? 'active' : ''}" data-site-id="${escapeHtml(site.id)}" type="button"><strong>${escapeHtml(site.name)}</strong><small>${escapeHtml(site.url || 'URL not provided')}</small><span class="webapp-item-meta"><span class="mini-status ${site.status === 'paused' ? 'paused' : ''}">● ${site.status === 'paused' ? 'PAUSED' : 'READY'}</span><span>${site.users || 0} users</span></span></button>`).join(''); }
  function siteState(site) { const saved = localState[site.id] || {}; return { ...site, ...saved, status: saved.status || site.status || 'ready' }; }
  function serverUrl(site) { return localStorage.getItem(`${SERVER_URL_PREFIX}${site.id}`) || String(site.serverUrl || ''); }
  function endpointName(site) { return localStorage.getItem(`${ENDPOINT_PREFIX}${site.id}`) || String(site.endpoint || 'health'); }
  function remoteState(site) { return remoteStates[site.id] || null; }
  function remotePaused(site, state) { const paused = state?.data?.paused || {}; return Boolean(paused[endpointName(site)] || paused[`/${endpointName(site)}`]); }
  function renderConnection(site) {
    const state = remoteState(site);
    $('xiServerUrl').value = serverUrl(site);
    $('xiEndpoint').value = endpointName(site);
    $('remoteState').textContent = state?.connected ? 'LIVE' : 'NOT CONNECTED';
    $('remoteState').classList.toggle('remote-live', Boolean(state?.connected));
    $('connectionLabel').textContent = state?.connected ? 'XI server connected' : 'Local simulation';
    $('safeMode').innerHTML = state?.connected ? '<span class="safe-icon">✓</span><div><strong>Live XI control active</strong><p>Status and endpoint lifecycle actions now come from the registered server.</p></div>' : '<span class="safe-icon">✓</span><div><strong>Local simulation active</strong><p>Connect an XI server above to control the registered webapp itself.</p></div>';
    $('actionEndpoint').textContent = state?.connected ? `${serverUrl(site)} · /${endpointName(site)}` : 'XI server not configured';
    $('actionEndpointHelp').textContent = state?.connected ? 'Authenticated with the server session; pairing secret is no longer held by this page.' : 'No remote request will be sent until a live XI server is connected.';
    document.querySelectorAll('[data-action="pause"], [data-action="resume"]').forEach(button => { button.disabled = Boolean(state?.connected && Array.isArray(state.data?.capabilities) && !state.data.capabilities.includes(button.dataset.action)); });
  }
  function renderSite() { const site = siteState(currentSite()); const remote = remoteState(site); const paused = remote ? remotePaused(site, remote) : site.status === 'paused'; $('siteName').textContent = site.name; $('siteUrl').textContent = site.url || 'No URL registered'; $('siteEnvironment').textContent = site.environment || 'REGISTERED'; $('siteHeartbeat').textContent = `heartbeat ${remote?.data?.siteDigest?.observations ? `${remote.data.siteDigest.observations}/2 observations` : (site.heartbeat || 'not reported')}`; $('siteStatus').textContent = paused ? 'PAUSED' : 'READY'; $('siteStatus').classList.toggle('paused', paused); $('healthStatus').textContent = paused ? 'PAUSED' : 'HEALTHY'; $('healthStatus').classList.toggle('paused', paused); $('endpointHealth').textContent = paused ? `503 / ${remote ? 'paused on server' : 'paused locally'}` : `200 / ${remote ? 'server verified' : 'healthy'}`; $('deploymentDigest').textContent = remote?.data?.siteDigest?.digest || site.digest || 'sha256:unavailable'; $('siteVersion').textContent = remote?.data?.version ? `XI server v${remote.data.version}` : (site.version || 'unreported'); $('lastDeploy').textContent = site.lastDeploy || 'unreported'; $('activeUsers').textContent = remote ? '—' : (paused ? '0' : site.users ?? '—'); $('connectedClients').textContent = remote ? '—' : (paused ? '0' : site.clients ?? '—'); $('requestsPerMinute').textContent = remote ? '—' : (paused ? '0' : site.rpm ?? '—'); $('errorRate').textContent = remote ? '—' : (site.errors ?? '—'); $('clientState').textContent = remote ? 'LIVE SESSIONS NOT EXPOSED' : (paused ? 'CLIENTS PAUSED' : 'DEMO TELEMETRY'); $('clientTable').innerHTML = remote ? `<tr><td><span class="session-user">XI server</span><span class="session-id">${escapeHtml(endpointName(site))}</span></td><td>Server status channel</td><td>Remote</td><td class="mono">just checked</td><td><span class="client-state ${paused ? 'idle' : ''}">${paused ? 'PAUSED' : 'CONNECTED'}</span></td></tr>` : CLIENTS.map(client => `<tr><td><span class="session-user">${client[0]}</span><span class="session-id">${client[1]}</span></td><td>${client[2]}</td><td>${client[3]}</td><td class="mono">${client[4]}</td><td><span class="client-state ${client[5] === 'IDLE' || paused ? 'idle' : ''}">${paused ? 'PAUSED' : client[5]}</span></td></tr>`).join(''); renderConnection(site); renderList(); }
  function events() { return localState[currentSite().id]?.events || [{ title:'Heartbeat received', detail:'Demo telemetry connected · 200 OK', time:'12 sec ago' }, { title:'Deployment verified', detail:'Digest matches registered release', time:'18 min ago' }, { title:'Operator session opened', detail:'Local simulation mode', time:'Today, 13:44' }]; }
  function renderEvents() { $('activityFeed').innerHTML = events().slice(0,8).map(event => `<article class="timeline-item"><span class="timeline-dot"></span><div><strong>${escapeHtml(event.title)}</strong><p>${escapeHtml(event.detail)}</p></div><time class="timeline-time">${escapeHtml(event.time)}</time></article>`).join(''); }
  function showToast(message) { $('toast').textContent = message; $('toast').classList.add('visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').classList.remove('visible'), 3200); }
  function addEvent(title, detail) { const id = currentSite().id; const state = localState[id] || {}; state.events = [{ title, detail, time:'just now' }, ...events()]; localState[id] = state; write(STATE_KEY, localState); renderEvents(); }
  function confirmAction(title, copy, callback) { $('dialogTitle').textContent = title; $('dialogCopy').textContent = copy; const dialog = $('operatorDialog'); $('dialogConfirm').onclick = () => { callback(); dialog.close(); }; dialog.showModal(); }
  async function requestRemote(site, action, path = '') { const base = serverUrl(site); if (!base) throw new Error('Set the XI server URL first.'); const url = new URL(base); url.searchParams.set('action', action); if (path) url.searchParams.set('path', path.replace(/^\/+/, '')); const tokenKey = `xi.webapps.bootstrap-token.${site.id}`; const token = sessionStorage.getItem(tokenKey) || $('xiDashboardToken').value.trim(); const headers = { Accept:'application/json' }; if (token) headers.Authorization = `Bearer ${token}`; const response = await fetch(url, { method:['pause','resume'].includes(action) ? 'PUT' : 'GET', credentials:'include', headers }); const text = await response.text(); let data; try { data = JSON.parse(text); } catch { data = { error:text }; } if (!response.ok) { if (response.status === 401) { sessionStorage.removeItem(tokenKey); $('xiDashboardToken').value = ''; remoteStates[site.id] = null; } throw new Error(`${response.status} ${data.error || response.statusText}`); } if (token) { sessionStorage.removeItem(tokenKey); $('xiDashboardToken').value = ''; } return data; }
  async function liveSnapshot(site) { const status = await requestRemote(site, 'status'); let manifest = {}; try { manifest = await requestRemote(site, 'manifest'); } catch { /* status remains useful when manifest is unavailable */ } return { ...status, ...manifest, paused:status.paused, siteDigest:status.siteDigest || manifest.siteDigest }; }
  async function connectXI() { const site = currentSite(); const url = $('xiServerUrl').value.trim(); const endpoint = $('xiEndpoint').value.trim() || 'health'; if (!url) return showToast('Set the XI server URL first'); try { new URL(url); } catch { return showToast('Enter a valid HTTP(S) XI server URL'); } localStorage.setItem(`${SERVER_URL_PREFIX}${site.id}`, url); localStorage.setItem(`${ENDPOINT_PREFIX}${site.id}`, endpoint); const token = $('xiDashboardToken').value.trim(); if (token) sessionStorage.setItem(`xi.webapps.bootstrap-token.${site.id}`, token); $('remoteState').textContent = 'CONNECTING'; try { remoteStates[site.id] = { connected:true, data:await liveSnapshot(site) }; renderSite(); renderEvents(); showToast('Connected to the XI server'); } catch (error) { remoteStates[site.id] = null; renderSite(); showToast(`XI connection failed: ${error.message}`); } }
  async function refreshXI() { const site = currentSite(); if (!serverUrl(site)) return showToast('Set the XI server URL first'); try { remoteStates[site.id] = { connected:true, data:await liveSnapshot(site) }; renderSite(); showToast('Live XI status refreshed'); } catch (error) { showToast(`XI refresh failed: ${error.message}`); } }
  function runAction(action) { const site = currentSite(); const remote = remoteState(site); if (action === 'pause' || action === 'resume') { const next = action === 'pause' ? 'paused' : 'ready'; confirmAction(`${action === 'pause' ? 'Pause' : 'Resume'} ${site.name}?`, remote ? `This sends a real ${action} request to the XI server for /${endpointName(site)}.` : action === 'pause' ? 'New sessions will be marked paused in this local simulation.' : 'Sessions will be marked ready again in this local simulation.', async () => { try { if (remote) { await requestRemote(site, action, endpointName(site)); remoteStates[site.id] = { connected:true, data:await liveSnapshot(site) }; addEvent(`Webapp ${action}d`, `XI server · /${endpointName(site)}`); renderSite(); showToast(`Webapp ${action}d on the XI server`); } else { localState[site.id] = { ...(localState[site.id] || {}), status:next, events:localState[site.id]?.events }; write(STATE_KEY, localState); addEvent(action === 'pause' ? 'Webapp paused' : 'Webapp resumed', 'Local simulation · no remote request sent'); renderSite(); showToast(action === 'pause' ? 'Webapp paused locally' : 'Webapp resumed locally'); } } catch (error) { showToast(`XI ${action} failed: ${error.message}`); } }); return; } if (action === 'notice') { if (remote) return showToast('The connected XI server does not expose broadcast notices yet. No request was sent.'); const dialog = $('noticeDialog'); $('noticeInput').value = 'Planned maintenance begins at 22:00 UTC.'; $('noticeConfirm').onclick = event => { event.preventDefault(); const message = $('noticeInput').value.trim(); if (message) { addEvent('Maintenance notice drafted', message); showToast('Notice added to local audit feed'); } dialog.close(); }; dialog.showModal(); return; } if (action === 'refresh') { if (remote) return refreshXI(); addEvent('Client refresh requested', 'Local simulation · 4 demo sessions marked for refresh'); showToast('Refresh request simulated locally'); } }
  function init() { const params = new URLSearchParams(location.search); selected = params.get('site') || sites[0].id; if (!sites.some(site => site.id === selected)) selected = sites[0].id; const theme = localStorage.getItem(THEME_KEY) || 'dark'; document.documentElement.dataset.theme = theme; renderSite(); renderEvents(); if (serverUrl(currentSite())) refreshXI(); $('webappList').addEventListener('click', event => { const item = event.target.closest('[data-site-id]'); if (!item) return; selected = item.dataset.siteId; const url = new URL(location.href); url.searchParams.set('site', selected); history.replaceState(null, '', url); renderSite(); renderEvents(); if (serverUrl(currentSite())) refreshXI(); }); document.querySelector('.action-list').addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (button && !button.disabled) runAction(button.dataset.action); }); $('connectXI').addEventListener('click', connectXI); $('refreshXI').addEventListener('click', refreshXI); $('clearEvents').addEventListener('click', () => { const id = currentSite().id; localState[id] = { ...(localState[id] || {}), events:[] }; write(STATE_KEY, localState); renderEvents(); showToast('Local activity feed cleared'); }); $('themeToggle').addEventListener('click', () => { const next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = next; localStorage.setItem(THEME_KEY, next); }); }
  document.addEventListener('DOMContentLoaded', init);
})();
